# -*- coding: utf-8 -*-
"""Api_textCrawl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dyxs8wxQOe3-NZhYpZVEA1Mr5yR2qiBC

# Text crawl use 
> Library `request`

> Use API [here's API](https://dummyjson.com/docs/products)

# import library
"""

import requests as req
import pandas as pd

# Tutorial https://pypi.org/project/requests/
crawl_text=req.get("https://dummyjson.com/products")

crawl_text.status_code

"""Status code 200 Everything went okay, and the result has been returned """

data_crawl=crawl_text.json() # Optional arguments that json.loads takes.

"""> API best practise use type data Json

>but in library request can use .text 

>but in practice just use .json 
"""

data_crawl

data_crawl_to_dataFrame=data_crawl['products']

data_crawl_fix=pd.DataFrame(data_crawl_to_dataFrame)

data_crawl_fix.to_csv("crawl_dummy_json.csv",index=False)

"""## Read data 
> Doing some text analysis
"""

data=pd.read_csv("/content/crawl_dummy_json.csv")

data

"""## Data Cleaning"""

data.drop(columns=["thumbnail","images"],inplace=True)

data